<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            //mas vendidos
            array( 
                'nombre' =>  "Alan Wake 2",
                'precio' => 873,
                'imagen' => "alan_wake_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Black Myth: Wukong",
                'precio' => 999,
                'imagen' => "black_myth_wukong",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "fc_24",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "gta_5",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Red Dead Redemption 2",
                'precio' => 1299,
                'imagen' => "red_dead_redemption_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Midnight Suns",
                'precio' => 1299,
                'imagen' => "marvels_midnight_suns",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cyberpunk 2077",
                'precio' => 1504.99,
                'imagen' => "cyberpunk_2077",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead by Daylight",
                'precio' => 299.85,
                'imagen' => "dead_by_daylight",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chivalry 2",
                'precio' => 323.99,
                'imagen' => "chivalry_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Manor Lords",
                'precio' => 499.99,
                'imagen' => "manor_lords",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "God of War",
                'precio' => 829,
                'imagen' => "god_of_war",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Horizon Forbidden West",
                'precio' => 999,
                'imagen' => "horizon_forbidden_west",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead Island 2",
                'precio' => 950,
                'imagen' => "dead_island_2",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hogwarts Legacy",
                'precio' => 999,
                'imagen' => "hogwarts_legacy",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Assassin's Creed Mirage",
                'precio' => 999,
                'imagen' => "assassins_creed_mirage",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Spider-Man Remastered",
                'precio' => 999,
                'imagen' => "spider_man_remastered",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //mas jugados
            array( 
                'nombre' =>  "Fortnite",
                'precio' => 0,
                'imagen' => "fortnite",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rocket League",
                'precio' => 0,
                'imagen' => "rocket_league",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "gta_5",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Wuthering Waves",
                'precio' => 0,
                'imagen' => "wuthering_waves",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Farming Simulator 22",
                'precio' => 539,
                'imagen' => "farming_simulator_22",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "VALORANT",
                'precio' => 0,
                'imagen' => "valorant",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Genshin Impact",
                'precio' => 0,
                'imagen' => "genshin_impact",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chivalry 2",
                'precio' => 323.99,
                'imagen' => "chivalry_2",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "fc_24",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Honkai: Star Rail",
                'precio' => 0,
                'imagen' => "honkai_star_rail",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "naraka_bladepoint",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Midnight Suns",
                'precio' => 1299,
                'imagen' => "marvels_midnight_suns",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Sid Meier's Civilization VI",
                'precio' => 599,
                'imagen' => "sid_meiers_civilization_vi",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fall Guys",
                'precio' => 0,
                'imagen' => "fall_guys",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "The Sims 4",
                'precio' => 0,
                'imagen' => "the_sims_4",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Destiny 2",
                'precio' => 0,
                'imagen' => "destiny_2",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //destacados orden alfabetico
            array( 
                'nombre' =>  "'n Verlore Verstand",
                'precio' => 133.99,
                'imagen' => "verlore_verstand",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "7 Billion Humans",
                'precio' => 156.99,
                'imagen' => "7_billion_humans",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "8Doors: Arum's Afterlife Adventure",
                'precio' => 161.99,
                'imagen' => "8doors",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Good Snowman Is Hard To Build",
                'precio' => 133.99,
                'imagen' => "a_good_snowman_is_hard_to_build",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A long Journey to an Uncertain End",
                'precio' => 222.99,
                'imagen' => "a_long_journey_to_an_uncertain_end",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Monster's Expedition",
                'precio' => 222.99,
                'imagen' => "a_monsters_expedition",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Plague Tale: Requiem",
                'precio' => 699.99,
                'imagen' => "a_plague_tale",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Total War Saga: TROY",
                'precio' => 730,
                'imagen' => "a_total_war_saga",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "ABZÚ",
                'precio' => 156.99,
                'imagen' => "abzu",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ad Infinitum",
                'precio' => 409.99,
                'imagen' => "ad_infinitum",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aeon Must Die!",
                'precio' => 269.99,
                'imagen' => "aeon_must_die",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "AER Memories of Old",
                'precio' => 122.99,
                'imagen' => "aer_memories_of_old",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aerial_Knight's Never Yield",
                'precio' => 133.99,
                'imagen' => "aerial_knights",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Against the Storm",
                'precio' => 399.99,
                'imagen' => "against_the_storm",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ageless",
                'precio' => 156.99,
                'imagen' => "ageless",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aground",
                'precio' => 120.99,
                'imagen' => "aground",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //nuevos lanzamientos
            array( 
                'nombre' =>  "Ghost of Tsushima",
                'precio' => 999,
                'imagen' => "ghost_of_tsushima",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "F1 24",
                'precio' => 1299,
                'imagen' => "f1_24",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Manor Lords",
                'precio' => 499.99,
                'imagen' => "manor_lords",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Horizon Forbidden West",
                'precio' => 999,
                'imagen' => "horizon_forbidden_west",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed Heat",
                'precio' => 1599,
                'imagen' => "need_for_speed_heat",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hades II",
                'precio' => 334.99,
                'imagen' => "hades_ii",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Battlefield 1 Revolution",
                'precio' => 899,
                'imagen' => "battlefield_1_revolution",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Suicide Squad",
                'precio' => 99,
                'imagen' => "suicide_squad",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "SKULL AND BONES",
                'precio' => 1199,
                'imagen' => "skull_and_bones",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Crosshair X",
                'precio' => 71.99,
                'imagen' => "crosshair_x",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed",
                'precio' => 639,
                'imagen' => "need_for_speed",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Battlefieled 4",
                'precio' => 899,
                'imagen' => "battlefield_4",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Avatar: Frontiers of Pandora",
                'precio' => 1399,
                'imagen' => "avatar",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed Most Wanted",
                'precio' => 439,
                'imagen' => "need_for_speed_most_wanted",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fallout 4",
                'precio' => 359,
                'imagen' => "fallout_4",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Titanfall 2",
                'precio' => 639,
                'imagen' => "titanfall_2",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //juegos gratuitos
            array( 
                'nombre' =>  "Fortnite",
                'precio' => 0,
                'imagen' => "fortnite",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rocket League",
                'precio' => 0,
                'imagen' => "rocket_league",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Wuthering Waves",
                'precio' => 0,
                'imagen' => "wuthering_waves",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Genshin Impact",
                'precio' => 0,
                'imagen' => "genshin_impact",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Honkai: Star Rail",
                'precio' => 0,
                'imagen' => "honkai_star_rail",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fall Guys",
                'precio' => 0,
                'imagen' => "fall_guys",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "The Sims 4",
                'precio' => 0,
                'imagen' => "the_sims_4",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Destiny 2",
                'precio' => 0,
                'imagen' => "destiny_2",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "MultiVersus",
                'precio' => 0,
                'imagen' => "multiversus",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Valorant",
                'precio' => 0,
                'imagen' => "valorant",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "naraka_bladepoint",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "PUBG: BATTLEGROUNDS",
                'precio' => 0,
                'imagen' => "pubg_battlegrounds",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Idle Champions of the Forgotten Realms",
                'precio' => 0,
                'imagen' => "idle_champions_of_the_forgotten_realms",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Firestone Online Idle RPG",
                'precio' => 0,
                'imagen' => "firestone_online_idle_rpg",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Warframe",
                'precio' => 0,
                'imagen' => "warframe",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dauntless",
                'precio' => 0,
                'imagen' => "dauntless",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //mas populares
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "gta_5",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Farming Simulator 22",
                'precio' => 539,
                'imagen' => "farming_simulator_22",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "VALORANT",
                'precio' => 0,
                'imagen' => "valorant",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "fc_24",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "naraka_bladepoint",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Red Dead Redemption 2",
                'precio' => 1299,
                'imagen' => "red_dead_redemption_2",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead by Daylight",
                'precio' => 299.85,
                'imagen' => "dead_by_daylight",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bloons TD 6",
                'precio' => 149.99,
                'imagen' => "bloons_td_6",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Among Us",
                'precio' => 39.99,
                'imagen' => "among_us",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dragon Age: Inquisition",
                'precio' => 729,
                'imagen' => "dragon_age_inquisition",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dying Light Definitive Edition",
                'precio' => 749,
                'imagen' => "dying_light_definitive_edition",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tom Clancy's Rainbow Six Siege",
                'precio' => 399,
                'imagen' => "r6",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cyberpunk 2077",
                'precio' => 1999,
                'imagen' => "cyberpunk_2077",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "League of Legends",
                'precio' => 0,
                'imagen' => "lol",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "STAR WARS Battlefront II",
                'precio' => 899,
                'imagen' => "star_wars_battlefront_ii",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Magic: The Gathering Arena",
                'precio' => 0,
                'imagen' => "magic_the_gathering_arena",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            
        ];

        DB::table('productos')->insert($datos);
    }
}
