<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $datos = [
            //mas vendidos
            array( 
                'nombre' =>  "Alan Wake 2",
                'precio' => 873,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Black Myth: Wukong",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Red Dead Redemption 2",
                'precio' => 1299,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Midnight Suns",
                'precio' => 1299,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cyberpunk 2077",
                'precio' => 1504.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead by Daylight",
                'precio' => 299.85,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chivalry 2",
                'precio' => 323.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Manor Lords",
                'precio' => 499.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "God of War",
                'precio' => 829,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Horizon Forbidden West",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead Islind 2",
                'precio' => 950,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hogwarts Legacy",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Assassin's Creed Mirage",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Spider-Man Remastered",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 1,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //mas jugados
            array( 
                'nombre' =>  "Fortnite",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rocket League",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Wuthering Waves",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Farming Simulator 22",
                'precio' => 539,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "VALORANT",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Genshin Impact",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Chivalry 2",
                'precio' => 323.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Honkai: Star Rail",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Marvel's Midnight Suns",
                'precio' => 1299,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Sid Meier's Civilization VI",
                'precio' => 599,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fall Guys",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "The Sims 4",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Destiny 2",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 2,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //destacados orden alfabetico
            array( 
                'nombre' =>  "'n Verlore Verstand",
                'precio' => 133.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "7 Billion Humans",
                'precio' => 156.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "8Doors: Arum's Afterlife Adventure",
                'precio' => 161.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Good Snowman Is Hard To Build",
                'precio' => 133.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A long Journey to an Uncertain End",
                'precio' => 222.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Monster's Expedition",
                'precio' => 222.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Plague Tale: Requiem",
                'precio' => 699.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "A Total War Saga: TROY",
                'precio' => 730,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "ABZÚ",
                'precio' => 156.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ad Infinitum",
                'precio' => 409.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aeon Must Die!",
                'precio' => 269.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "AER Memories of Old",
                'precio' => 122.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aerial_Knight's Never Yield",
                'precio' => 133.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Against the Storm",
                'precio' => 399.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Ageless",
                'precio' => 156.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Aground",
                'precio' => 120.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 3,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //nuevos lanzamientos
            array( 
                'nombre' =>  "Ghost of Tsushima",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "F1 24",
                'precio' => 1299,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Manor Lords",
                'precio' => 499.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Horizon Forbidden West",
                'precio' => 999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed Heat",
                'precio' => 1599,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Hades II",
                'precio' => 334.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Battlefield 1 Revolution",
                'precio' => 899,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Suicide Squad",
                'precio' => 99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "SKULL AND BONES",
                'precio' => 1199,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Crosshair X",
                'precio' => 71.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed",
                'precio' => 639,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Battlefieled 4",
                'precio' => 899,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Avatar: Frontiers of Pandora",
                'precio' => 1399,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Need for Speed Most Wanted",
                'precio' => 439,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fallout 4",
                'precio' => 359,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Titanfall 2",
                'precio' => 639,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 4,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //juegos gratuitos
            array( 
                'nombre' =>  "Fortnite",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Rocket League",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Wuthering Waves",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Genshin Impact",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Honkai: Star Rail",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Fall Guys",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "The Sims 4",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Destiny 2",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "MultiVersus",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Valorant",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "PUBG: BATTLEGROUNDS",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Idle Champions of the Forgotten Realms",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Firestone Online Idle RPG",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Warfreame",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dauntless",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 5,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            //mas populares
            array( 
                'nombre' =>  "Grand Theft Auto V",
                'precio' => 599,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Farming Simulator 22",
                'precio' => 539,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "VALORANT",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "EA SPORTS FC 24",
                'precio' => 1099,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "NARAKA: BLADEPOINT",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Red Dead Redemption 2",
                'precio' => 1299,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dead by Daylight",
                'precio' => 299.85,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Bloons TD 6",
                'precio' => 149.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Among Us",
                'precio' => 39.99,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dragon Age: Inquisition",
                'precio' => 729,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Dying Light Definitive Edition",
                'precio' => 749,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Tom Clancy's Rainbow Six Siege",
                'precio' => 399,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Cyberpunk 2077",
                'precio' => 1999,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "League of Legends",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "STAR WARS Battlefront II",
                'precio' => 899,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            array( 
                'nombre' =>  "Magic: The Gathering Arena",
                'precio' => 0,
                'imagen' => "hamburguesas_01",
                'categoria_id' => 6,
                'disponible' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ),
            
        ];

        DB::table('productos')->insert($datos);
    }
}
